### ISSUE TITLE
Get Null Pointer exception when generating Stripe connector

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#1231]
**Description:**
$subject
```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-03-16 09:55:53,810] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.openapi.core.generators.schema.ballerinatypegenerators.ArrayTypeGenerator.generateTypeDescriptorNode(ArrayTypeGenerator.java:95)
        at io.ballerina.openapi.core.generators.schema.ballerinatypegenerators.RecordTypeGenerator.getRecordRestDescriptorNode(RecordTypeGenerator.java:224)
        at io.ballerina.openapi.core.generators.schema.ballerinatypegenerators.RecordTypeGenerator.getRecordMetadata(RecordTypeGenerator.java:164)
        at io.ballerina.openapi.core.generators.schema.ballerinatypegenerators.RecordTypeGenerator.generateTypeDescriptorNode(RecordTypeGenerator.java:116)
        at io.ballerina.openapi.core.generators.schema.ballerinatypegenerators.RecordTypeGenerator.addRecordFields(RecordTypeGenerator.java:256)
        at io.ballerina.openapi.core.generators.schema.ballerinatypegenerators.RecordTypeGenerator.generateTypeDescriptorNode(RecordTypeGenerator.java:121)
        at io.ballerina.openapi.core.generators.schema.ballerinatypegenerators.TypeGenerator.generateTypeDefinitionNode(TypeGenerator.java:73)
        at io.ballerina.openapi.core.generators.schema.BallerinaTypesGenerator.getTypeDefinitionNode(BallerinaTypesGenerator.java:236)
        at io.ballerina.openapi.core.generators.schema.BallerinaTypesGenerator.generateSyntaxTree(BallerinaTypesGenerator.java:143)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClientFiles(BallerinaCodeGenerator.java:360)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClient(BallerinaCodeGenerator.java:215)
        at io.ballerina.openapi.cmd.OpenApiCmd.generatesClientFile(OpenApiCmd.java:355)
        at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:283)
        at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:183)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Steps to reproduce:**
Generate client using the openapi [here](https://github.com/ballerina-platform/openapi-connectors/blob/main/openapi/stripe/openapi.yaml)

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aneeshafedo** [comment]
Issue is probably due to the below openapi snippet which has array type additional property with constraints

```yaml
supported_bank_account_currencies:
          additionalProperties:
            items:
              maxLength: 5000
              type: string
            type: array
          description: Currencies that can be accepted in the specific country (for
            transfers).
          type: object```

**Comment by lnash94** [comment]
Close https://github.com/ballerina-platform/openapi-tools/pull/1235
