### ISSUE TITLE
Getting null point when path parameter has `AnyOf` schema

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#1247]
**Description:**
sample openapi
```openapi
openapi: 3.1.0
info:
  title: V4
  version: 0.1.0
servers:
  - url: http://localhost
paths:
  /pet/{id}:
    post:
      operationId: operation_post_/pet
      parameters:
        - name: id
          in: path
          description: Id of the point
          required: true
          schema:     
            anyOf:
              - type: integer
              - type: string
      responses:
        "202":
          description: Accepted
components:
  schemas:
    Param:
      anyOf:
        - type: integer
        - type: string
    Pet:
      type: object
      properties:
        name:
          type: string
        owned_by:
          type: string
```
Stack trace:
```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-03-22 12:50:31,347] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.openapi.core.generators.client.FunctionSignatureGenerator.getPathParameters(FunctionSignatureGenerator.java:374)
        at io.ballerina.openapi.core.generators.client.FunctionSignatureGenerator.setFunctionParameters(FunctionSignatureGenerator.java:204)
        at io.ballerina.openapi.core.generators.client.FunctionSignatureGenerator.getFunctionSignatureNode(FunctionSignatureGenerator.java:151)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.getClientMethodFunctionDefinitionNode(BallerinaClientGenerator.java:563)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.createRemoteFunctions(BallerinaClientGenerator.java:501)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.getClassDefinitionNode(BallerinaClientGenerator.java:256)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.generateSyntaxTree(BallerinaClientGenerator.java:214)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClientFiles(BallerinaCodeGenerator.java:334)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClient(BallerinaCodeGenerator.java:205)
        at io.ballerina.openapi.cmd.OpenApiCmd.generatesClientFile(OpenApiCmd.java:352)
        at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:280)
        at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:180)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
Reference OpenAPI spec : https://github.com/qdrant/qdrant/blob/master/docs/redoc/master/openapi.json#L1981
**Steps to reproduce:**
run the client generator command
`bal run openapi -i <sample.yaml> --mode client`
**Affected Versions:**
2201.4.0
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
Suggested Client resource method to generate from tool:
```ballerina
resource isolated function get pet/[int|string id]() returns string|error {
        string resourcePath = string `/pet/${id}`;
        string response = check self.clientEp->/pet/[id].get;
        // string response = check self.clientEp->get(resourcePath);
        return response;
    }
```

**Comment by lnash94** [comment]
When we wrote **a service with resource functions with a union path parameter** [1] it gives a compilation error [2] 
[1] http service with a union path parameter
```ballerina
import ballerina/http;
service / on new http:Listener(9090) {

    resource function get pet/[string|int id]() returns string {
        return "Hi there..";
    }
}
```
[2] compilation error for service resource 
```
error: incompatible path parameter type: ''
```

If we wrote **client with resource method with union path parameter**[3] it doesn't give a compilation error
[3] client with union resource path parameter
```ballerina
import ballerina/http;

public isolated client class Client {
    final http:Client clientEp;
    
-----
    resource isolated function get pet/[int|string id]() returns string|error {
        string resourcePath = string `/pet/${id}`;
        string response = check self.clientEp->get(resourcePath);
        return response;
    }
}
```
As mentioned in the parent issue https://github.com/ballerina-platform/ballerina-standard-library/issues/4216#issue-1627054858  we found API which allows union type as a path parameter. Therefore current connector code generation has no issue with union-type data binding since we generate endpoint URLs inside the resource method.

 Reference to parent discussion: https://github.com/ballerina-platform/ballerina-standard-library/issues/4216#issuecomment-1473098182

**Comment by lnash94** [comment]
Today (2023/03/22) had a meeting with @shafreenAnfar , @TharmiganK and myself.
Meeting summary:

- Suggested resource method generation was approved for the client generator with the path union type support ([[3] point](https://github.com/ballerina-platform/openapi-tools/issues/1247#:~:text=%5B3%5D%20client%20with%20union%20resource%20path%20parameter))
- Concluded to not support union types as a resource path parameter in the **service**. Since what we get from the url is just the string path segment and from that value, it is not possible to find the exact type if we are using union types. So we will be only allowing a single basic type as a path parameter and will give proper compiler error from our plugin. ([[1]point](https://github.com/ballerina-platform/openapi-tools/issues/1247#:~:text=%5B1%5D%20http%20service%20with%20a%20union%20path%20parameter))
- Suggested generating type `string`,  If there is a path parameter type that is not supported from ballerina http in the service resource functions. 

Reference : https://github.com/ballerina-platform/ballerina-standard-library/issues/4216

**Comment by lnash94** [comment]
Close with this PR https://github.com/ballerina-platform/openapi-tools/pull/1313
