### ISSUE TITLE
Get NPE while generating client

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#1278]
**Description:**
Effected connector: https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/apideck.proxy
stack trace for :
```
[2023-04-03 13:32:53,047] SEVERE {b7a.log.crash} - begin 0, end 1, length 0 
java.lang.StringIndexOutOfBoundsException: begin 0, end 1, length 0
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at io.ballerina.openapi.core.GeneratorUtils.getValidName(GeneratorUtils.java:346)
        at io.ballerina.openapi.core.generators.schema.BallerinaTypesGenerator.getTypeDefinitionNode(BallerinaTypesGenerator.java:209)
        at io.ballerina.openapi.core.generators.client.FunctionSignatureGenerator.getRequestBodyParameterForObjectSchema(FunctionSignatureGenerator.java:582)
        at io.ballerina.openapi.core.generators.client.FunctionSignatureGenerator.setRequestBodyParameters(FunctionSignatureGenerator.java:527)
        at io.ballerina.openapi.core.generators.client.FunctionSignatureGenerator.setFunctionParameters(FunctionSignatureGenerator.java:239)
        at io.ballerina.openapi.core.generators.client.FunctionSignatureGenerator.getFunctionSignatureNode(FunctionSignatureGenerator.java:151)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.getClientMethodFunctionDefinitionNode(BallerinaClientGenerator.java:563)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.createRemoteFunctions(BallerinaClientGenerator.java:501)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.getClassDefinitionNode(BallerinaClientGenerator.java:256)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.generateSyntaxTree(BallerinaClientGenerator.java:214)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClientFiles(BallerinaCodeGenerator.java:334)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClient(BallerinaCodeGenerator.java:205)
        at io.ballerina.openapi.cmd.OpenApiCmd.generatesClientFile(OpenApiCmd.java:352)
        at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:280)
        at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:180)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
Affected connectors :
- apideck.proxy
- sinch.voice
- sugarcrm

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**
2201.3.0 - 2201.4.1

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
Yeah, normally we support empty objects with ballerina `record{}`. I'm confused with the previous code generation in the 2201.2.4 version since it gave the `json` as above mentioned scenario.

**Comment by aneeshafedo** [comment]
Also found in
- brex.team
- quickbase

**Comment by lnash94** [comment]
Following scenarios will be captured via this fix 

- [ ] 01. Request body has object schema content without the `properties` field
```openapi
   put:
      tags:
        - Files
      summary: Update File
      requestBody:
        content:
          application/json:
            schema:
              type: object
```
expected ballerina code
```ballerina
resource isolated function put api/files/[string id](record{} payload) returns json|error {
       string resourcePath = string `/api/files/${getEncodedUri(id)}`;
       http:Request request = new;
       request.setPayload(payload, "application/json");
       json response = check self.clientEp->put(resourcePath, request);
       return response;
   }
```
- [ ] 02. The Request body is with reference  to the reusable requestBody with content type has object without properties
```openapi
      put:
          operationId: updateGreeting
          requestBody:          
            $ref: '#/components/requestBodies/PetBody’
    …        
    components:
      requestBodies:
        PetBody:
          description: A JSON object containing pet information
          required: true
          content:
            application/json:
              schema:
                type: object
```
expected ballerina code
```ballerina
resource isolated function put greeting(record{} payload) returns Person|error {
        string resourcePath = string `/greeting`;
        http:Request request = new;
        json jsonBody = payload.toJson();
        request.setPayload(jsonBody, "application/json");
        Person response = check self.clientEp->put(resourcePath, request);
        return response;
    }
```
- [ ] 03. RequestBody has object content without properties with `application/xml`
```openapi
      post:
          operationId: addPerson
          requestBody:          
            content:
              application/xml:
                schema:
                  type: object
```
Expected ballerina code generation
```ballerina
resource isolated function post greeting(record{} payload) returns Person|error {
        string resourcePath = string `/greeting`;
        http:Request request = new;
        json jsonBody = payload.toJson();
        xml? xmlBody = check xmldata:fromJson(jsonBody);
        request.setPayload(xmlBody, "application/xml");
        Person response = check self.clientEp->post(resourcePath, request);
        return response;
    }
```

- [ ] 04. RequestBody has object content without properties with vendor-specific media type `vnd.petstore.v3.diff+json`
```openapi
    post:
          operationId: addPerson
          requestBody:          
            content:
              application/vnd.petstore.v3.diff+json:
                schema:
                  type: object

```
expected ballerina code generation
```ballerina
resource isolated function post greeting(record{} payload) returns Person|error {
        string resourcePath = string `/greeting`;
        http:Request request = new;
        request.setPayload(payload, "application/vnd.petstore.v3.diff+json");
        Person response = check self.clientEp->post(resourcePath, request);
        return response;
    }
```

- [ ] 05. Request body has non-standard media type  `application/zip` with object content without properties 
```openapi
      post:
          operationId: addPerson
          requestBody:          
            content:
              application/zip:
                schema:
                  type: object
```
expected ballerina code generation
```ballerina
resource isolated function post greeting(http:Request request) returns Person|error {
        string resourcePath = string `/greeting`;
        // TODO: Update the request as needed;
        Person response = check self.clientEp->post(resourcePath, request);
        return response;
    }
```

@NipunaRanasinghe , @aneeshafedo appreciate your thoughts regarding the above scenarios 🙂

**Comment by lnash94** [comment]
Close with this PR https://github.com/ballerina-platform/openapi-tools/pull/1313
