### ISSUE TITLE
Provide support for `pattern` constraint in openapi to ballerina code generation

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#1283]
**Description:**
Currently, constrain module has given support for pattern constraints in a string type with ballerina version 2201.4.0. Therefore we can give implements the support for pattern in OAS to Ballerina code generation.
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3179
openapi code sample
```openapi
      properties:
        nic:
          type: string
          pattern: "^[a-zA-Z0-9]*$"
```
relevant ballerina code with pattern constraints 

```ballerina
import ballerina/constraint;
type User record {
    @constraint:String {pattern: re `([0-9]{9}[v|V]|[0-9]{12})`}
     string nic;
}
```

scenarios for pattern constraint in ballerina
```ballerina
import ballerina/constraint;

string:RegExp regExp = re `([0-9]{10})|(\+[0-9]{11})`;

@constraint:String {pattern: regExp}
type PhoneNumber string;

type User record {|
    string name;
    @constraint:String {pattern: re `male|female`}
    string gender?;
    int age;
    @constraint:String {pattern: re `([0-9]{9}[v|V]|[0-9]{12})`}
    string nic;
|};

type UserAdvanced record {|
    *User;
    PhoneNumber contactNumber;
    @constraint:String {pattern: re `([a-zA-Z0-9._%\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,6})*`}
    string email;
|};
```
**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
These pattern constraints can be found in 

- [ ] 01. Path parameters
- [ ] 02. Query Parameter
- [ ] 03. Header parameters
- [ ] 04. String type record field 

Here above 01-03 can not give support for constraint since the current constraint only support for scenario 04.

**Comment by lnash94** [comment]
> These pattern constraints can be found in
> 
> * [ ]  01. Path parameters
> * [ ]  02. Query Parameter
> * [ ]  03. Header parameters
> * [x]  04. String type record field
> 
> Here above 01-03 can not give support for constraint since the current constraint only support for scenario 04.
> 
> * [x]  Test with the openAPI connectors repo

The following connectors have a pattern that we can not directly use into ballerina regex

- [alfresco](https://github.com/ballerina-platform/openapi-connectors/blob/47259268c32c7c5a4a8444f7ddfecff1d543a7ec/openapi/alfresco/openapi.yaml#L2307)
- [azure.iothub](https://github.com/ballerina-platform/openapi-connectors/blob/47259268c32c7c5a4a8444f7ddfecff1d543a7ec/openapi/azure.iothub/openapi.yml#L4055)
- [optimizely](https://github.com/ballerina-platform/openapi-connectors/blob/47259268c32c7c5a4a8444f7ddfecff1d543a7ec/openapi/optimizely/openapi.yaml#L5380)
- [optitune](https://github.com/ballerina-platform/openapi-connectors/blob/47259268c32c7c5a4a8444f7ddfecff1d543a7ec/openapi/optitune/openapi.yml#L6976)
- [power.bi](https://github.com/ballerina-platform/openapi-connectors/blob/47259268c32c7c5a4a8444f7ddfecff1d543a7ec/openapi/power.bi/openapi.yaml#L11891)
- [shortcut](https://github.com/ballerina-platform/openapi-connectors/blob/47259268c32c7c5a4a8444f7ddfecff1d543a7ec/openapi/shortcut/openapi.yml#L3345)

**Comment by lnash94** [comment]
- We can not support parameter level constraints since still we haven't support within the constraint module - https://github.com/ballerina-platform/ballerina-standard-library/issues/3239
- Currently, we used ballerina runtime API for checking the compatibility with the pattern support via Ballerina until we receive this API - https://github.com/ballerina-platform/ballerina-lang/issues/40318
- As mentioned in the previous [comments](https://github.com/ballerina-platform/openapi-tools/issues/1283#issuecomment-1523252270) we encountered some patterns we can not support via Ballerina although those have the same regex flavour. Therefore currently we are going to ignore the code generation for that pattern and we give a warning regarding the pattern.
reference issue : https://github.com/ballerina-platform/ballerina-lang/issues/40328

**Comment by lnash94** [comment]
While doing implementation we encounter this confusing warning-log[1], when the provided swagger has a regular expression with syntax errors that occur from the swagger parser.  Since it is not a generic warning and it has been handled within the third-party dependency we are unable to handle it within ourselves. 
Reference:  https://github.com/swagger-api/swagger-parser/issues/1923

[1] Warning-log
```
May 09, 2023 1:51:21 PM io.swagger.v3.parser.util.DeserializationUtils readYamlTree
WARNING: Error snake-parsing yaml content
io.swagger.v3.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000, maxYamlAliasesForCollections 2147483647)
        at io.swagger.v3.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:438)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:406)
        at io.swagger.v3.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:211)
        at io.swagger.v3.parser.util.DeserializationUtils.deserializeIntoTree(DeserializationUtils.java:143)
        at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:168)
        at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:107)
        at io.swagger.parser.OpenAPIParser.readContents(OpenAPIParser.java:29)
        at io.ballerina.openapi.core.GeneratorUtils.getOpenAPIFromOpenAPIV3Parser(GeneratorUtils.java:436)
        at io.ballerina.openapi.core.GeneratorUtils.normalizeOpenAPI(GeneratorUtils.java:734)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClientFiles(BallerinaCodeGenerator.java:333)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClient(BallerinaCodeGenerator.java:215)
        at io.ballerina.openapi.cmd.OpenApiCmd.generatesClientFile(OpenApiCmd.java:355)
        at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:283)
        at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:183)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
Caused by: while scanning a double-quoted scalar
 in 'string', line 71, column 20:
              pattern: "[a-zA-Z0-9,\\.\']" 
                       ^
found unknown escape character '(39)
 in 'string', line 71, column 36:
              pattern: "[a-zA-Z0-9,\\.\']" 
                                       ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarNonSpaces(ScannerImpl.java:1962)
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1895)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1075)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1057)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:445)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:256)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:680)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:171)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:190)
        at org.yaml.snakeyaml.composer.Composer.composeKeyNode(Composer.java:317)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:308)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:116)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
        at io.swagger.v3.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:415)
        ... 16 more
....
```
Tried to turn off the log ftm and wonder if it may affect not displaying openAPI tool's log itself because we have used the log for OpenAPI tool purposes.

At a glance having this warning makes the OpenAPI tool crash, I'm afraid that if we disable this warning, users may confuse with the tool without knowing the issue with their provided OpenAPI specification because, on our tooling side, we are unable to provide detailed error messages since we only receive generic errors for these scenarios from the swagger-parser message. 
Appreciate your thoughts regarding this @NipunaRanasinghe, @aneeshafedo :)
