### ISSUE TITLE
Check the behavior for OpenAPI versions `3.1.0`  and `3.0.1`

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#1332]
**Description:**
While trying out the below code pieces with openAPI version 3.1.0 and 3.0.1 it behaves in two different ways

### 01. With OpenAPI version 3.0.1 : path parameter has inline `anyOf` 
```openapi
openapi: 3.0.1
info:
  title: V4
  version: 0.1.0
servers:
  - url: http://localhost
paths:
  /pet/{id}:
    post:
      operationId: operation_post_/pet
      parameters:
        - name: id
          in: path
          description: Id of the point
          required: true
          schema:     
            anyOf:
              - type: integer
              - type: string
      responses:
        "202":
          description: Accepted
```
execute commands : `bal openapi -i <yaml>` , `bal openapi -i <yaml> --mode client`
output: generated ballerina codes as expected

### 02. With OpenAPI version 3.1.0 : path parameter has inline `anyOf` 
```openapi
openapi: 3.0.1
info:
  title: V4
  version: 0.1.0
servers:
  - url: http://localhost
paths:
  /pet/{id}:
    post:
      operationId: operation_post_/pet
      parameters:
        - name: id
          in: path
          description: Id of the point
          required: true
          schema:     
            anyOf:
              - type: integer
              - type: string
      responses:
        "202":
          description: Accepted
```
execute commands : `bal openapi -i <yaml>` , `bal openapi -i <yaml> --mode client`
output: command execution failed with stack traces 
```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-04-25 10:15:08,232] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.openapi.core.generators.client.FunctionSignatureGenerator.getPathParameters(FunctionSignatureGenerator.java:375)
        at io.ballerina.openapi.core.generators.client.FunctionSignatureGenerator.setFunctionParameters(FunctionSignatureGenerator.java:205)
        at io.ballerina.openapi.core.generators.client.FunctionSignatureGenerator.getFunctionSignatureNode(FunctionSignatureGenerator.java:152)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.getClientMethodFunctionDefinitionNode(BallerinaClientGenerator.java:563)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.createRemoteFunctions(BallerinaClientGenerator.java:501)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.getClassDefinitionNode(BallerinaClientGenerator.java:256)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.generateSyntaxTree(BallerinaClientGenerator.java:214)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClientFiles(BallerinaCodeGenerator.java:334)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClient(BallerinaCodeGenerator.java:205)
        at io.ballerina.openapi.cmd.OpenApiCmd.generatesClientFile(OpenApiCmd.java:352)
        at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:280)
        at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:180)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
Reason for the error:
OpenAPI version 3.1.0 gives inline `anyOf` type as a **JsonSchema** while OpenAPI version 3.0.1 is giving flattened schema references. 
These are two behaviour for these two versions although it has the same content.

**Comment by aneeshafedo** [comment]
Added an issue in the openapi-parser repository to get this fix from the parser. swagger-api/swagger-parser#1950

**Comment by aneeshafedo** [comment]
With the latest OpenAPI tool (U8) which has partial support for OpenAPI 3.1 specs, the client generated for such usecases contains compile time errors. 

**Sample OpenAPI:**

```yaml
  /pet:
    put:
      tags:
        - pet
      summary: Update an existing pet
      description: Update an existing pet by Id
      operationId: updatePet
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/Pet'
                  - $ref: '#/components/schemas/User'
```

**Generated Code : Missing return type**

```ballerina
    remote isolated function updatePet(Pet payload) returns |error {
        string resourcePath = string `/pet`;
        http:Request request = new;
        json jsonBody = payload.toJson();
        request.setPayload(jsonBody, "application/json");
         response = check self.clientEp->put(resourcePath, request);
        return response;
    }
```

The same operation generates correctly if the OpenAPI is written in v3.0.x
