### ISSUE TITLE
Bad Sad error when generating openapi definition from service.bal

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/openapi-tools#1357]
**Description:**

I am getting following error when generating openapi.yaml from my ballerina service. 

```
 ~/…/markertplace-openapi/to-share/latest|$ bal openapi -i /Users/hasithah/work/choreo-marketplace/marketplaceService.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-05-17 13:52:56,809] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
	at io.ballerina.openapi.converter.service.OpenAPIResponseMapper.lambda$addResponse$9(OpenAPIResponseMapper.java:774)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at io.ballerina.openapi.converter.service.OpenAPIResponseMapper.lambda$addResponse$10(OpenAPIResponseMapper.java:768)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.openapi.converter.service.OpenAPIResponseMapper.addResponse(OpenAPIResponseMapper.java:768)
	at io.ballerina.openapi.converter.service.OpenAPIResponseMapper.mapUnionReturns(OpenAPIResponseMapper.java:762)
	at io.ballerina.openapi.converter.service.OpenAPIResponseMapper.getAPIResponses(OpenAPIResponseMapper.java:482)
	at io.ballerina.openapi.converter.service.OpenAPIResponseMapper.getResourceOutput(OpenAPIResponseMapper.java:190)
	at io.ballerina.openapi.converter.service.OpenAPIResourceMapper.convertResourceToOperation(OpenAPIResourceMapper.java:225)
	at io.ballerina.openapi.converter.service.OpenAPIResourceMapper.getResourcePath(OpenAPIResourceMapper.java:112)
	at io.ballerina.openapi.converter.service.OpenAPIResourceMapper.getPaths(OpenAPIResourceMapper.java:89)
	at io.ballerina.openapi.converter.service.OpenAPIServiceMapper.convertServiceToOpenAPI(OpenAPIServiceMapper.java:73)
	at io.ballerina.openapi.converter.utils.ServiceToOpenAPIConverterUtils.generateOAS(ServiceToOpenAPIConverterUtils.java:243)
	at io.ballerina.openapi.converter.utils.ServiceToOpenAPIConverterUtils.generateOAS3Definition(ServiceToOpenAPIConverterUtils.java:120)
	at io.ballerina.openapi.cmd.OASContractGenerator.generateOAS3DefinitionsAllService(OASContractGenerator.java:115)
	at io.ballerina.openapi.cmd.OpenApiCmd.ballerinaToOpenApi(OpenApiCmd.java:231)
	at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:195)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Steps to reproduce:**

Use Ballerina 2201.5.0

Try to generate the openapi pointing to the service code (sent offline to @aneeshafedo )

**Affected Versions:**

Ballerina 2201.5.0

**Comment by lnash94** [comment]
Given that the sample file link was diable for now, we expected the error to occur due to the below error scenarios.
Reference issue discussion: https://discord.com/channels/957996897782616114/1108326862079406101/1108326862079406101
```ballerina
import ballerina/http;
service /payloadV on new http:Listener(9090) {

    # A resource for generating greetings
    # + name - the input string name
    # + return - string name with hello message or error
    resource function get greeting(string name) returns http:InternalServerError|error {
        return "Hello, " + name;
    }
}
```
