### ISSUE TITLE
Unable to build the connector generated for Zuora API

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#482]
**Description:**
Following compiler time error occurred when building the Zuora connector generated from Ballerina OpenAPI tool. 

```
[2021-08-06 18:03:11,223] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSameType(Types.java:341)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSameType(Types.java:306)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:636)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.checkRecordEquivalency(Types.java:1564)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.checkStructEquivalency(Types.java:1471)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:785)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isArrayTypesAssignable(Types.java:1152)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:805)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:631)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$resolveIncludedFields$33(SymbolEnter.java:4480)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.resolveIncludedFields(SymbolEnter.java:4492)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.resolveFields(SymbolEnter.java:3614)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineFieldsOfObjectOrRecordTypeDef(SymbolEnter.java:3552)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineFields(SymbolEnter.java:3506)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:404)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:318)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:275)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:268)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:377)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:174)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:166)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:95)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
        at io.ballerina.projects.Package.getCompilation(Package.java:135)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:64)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:302)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)```
```
Please find the Open API definition [here](https://github.com/APIs-guru/openapi-directory/blob/main/APIs/zuora.com/2021-07-30/openapi.yaml)
**Suggested Labels:**
> client

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by aneeshafedo** [comment]
This is a Ballerina language bug. 
https://github.com/ballerina-platform/ballerina-lang/issues/32044

**Comment by SanduDS** [comment]
The Zuora billing API can't be validated by the swagger editor. The OpenAPI 3.0.0 conversion also failed. Therefore Billing API spec will be recreated. other Zuora API has no issue in client generation.

**Comment by aneeshafedo** [comment]
We will generate multiple connectors for zuora API, grouping the resources
