### ISSUE TITLE
Handle when wildcard `*/*` media type is given in service generation

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#628]
**Description:**
OpenAPI code sample 
```
...
 responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AbuseTicket'
```
**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**
Client issue -> https://github.com/ballerina-platform/ballerina-openapi/issues/621

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aneeshafedo** [comment]
currently returns a NPE

```
java.lang.NullPointerException
        at io.ballerina.openapi.core.generators.service.RequestBodyGenerator.getNodeForPayloadType(RequestBodyGenerator.java:128)
        at io.ballerina.openapi.core.generators.service.RequestBodyGenerator.createNodeForRequestBody(RequestBodyGenerator.java:101)
        at io.ballerina.openapi.core.generators.service.BallerinaServiceGenerator.getResourceFunction(BallerinaServiceGenerator.java:243)
        at io.ballerina.openapi.core.generators.service.BallerinaServiceGenerator.applyFiltersForOperations(BallerinaServiceGenerator.java:206)
        at io.ballerina.openapi.core.generators.service.BallerinaServiceGenerator.createResourceFunctions(BallerinaServiceGenerator.java:154)
        at io.ballerina.openapi.core.generators.service.BallerinaServiceGenerator.generateSyntaxTree(BallerinaServiceGenerator.java:115)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClientAndService(BallerinaCodeGenerator.java:106)
        at io.ballerina.openapi.cmd.OpenApiCmd.generateBothFiles(OpenApiCmd.java:395)
        at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:286)
        at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:180)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
