### ISSUE TITLE
OpenAPI request body without schema gives an error

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#724]
**Description:**
The following openapi response schema returns an error

```yaml
      requestBody:
        description: ' '
        content:
          application/json: {}
```

```
indikas@indikas verizon.vehicleupdate % bal openapi --mode client -i openapi.yaml
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2021-11-12 23:01:27,249] SEVERE {b7a.log.crash} - Cannot invoke "io.swagger.v3.oas.models.media.Schema.get$ref()" because "schema" is null 
java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.media.Schema.get$ref()" because "schema" is null
	at io.ballerina.openapi.generators.client.FunctionSignatureGenerator.setRequestBodyParameters(FunctionSignatureGenerator.java:433)
	at io.ballerina.openapi.generators.client.FunctionSignatureGenerator.setFunctionParameters(FunctionSignatureGenerator.java:217)
	at io.ballerina.openapi.generators.client.FunctionSignatureGenerator.getFunctionSignatureNode(FunctionSignatureGenerator.java:133)
	at io.ballerina.openapi.generators.client.BallerinaClientGenerator.getRemoteFunctionDefinitionNode(BallerinaClientGenerator.java:502)
	at io.ballerina.openapi.generators.client.BallerinaClientGenerator.createRemoteFunctions(BallerinaClientGenerator.java:455)
	at io.ballerina.openapi.generators.client.BallerinaClientGenerator.getClassDefinitionNode(BallerinaClientGenerator.java:230)
	at io.ballerina.openapi.generators.client.BallerinaClientGenerator.generateSyntaxTree(BallerinaClientGenerator.java:190)
	at io.ballerina.openapi.cmd.CodeGenerator.generateClient(CodeGenerator.java:452)
	at io.ballerina.openapi.cmd.CodeGenerator.generateBalSource(CodeGenerator.java:257)
	at io.ballerina.openapi.cmd.CodeGenerator.generate(CodeGenerator.java:143)
	at io.ballerina.openapi.cmd.CodeGenerator.generateClient(CodeGenerator.java:183)
	at io.ballerina.openapi.cmd.OpenApiCmd.generatesClientFile(OpenApiCmd.java:281)
	at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:210)
	at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:140)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aneeshafedo** [comment]
**Sample OpenAPI**
```yaml
/pets:
    post:
      summary: List all pets
      description: Show a list of pets in the system
      operationId: listPets
      tags:
        - pets
        - list
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      requestBody:
        description: Pet
        content:
          application/json: {}
      responses:
        '200':
          description: ''
          content:
            application/json: {}
```
**Suggested code implementation** 

```bal
remote isolated function listPets(json payload, int? 'limit = ()) returns json|error {
        string path = string `/pets`;
        map<anydata> queryParam = {"limit": 'limit};
        path = path + check getPathForQueryParam(queryParam);
        http:Request request = new;
        request.setPayload(payload, "application/json");
        json response = check self.clientEp->post(path, request);
        return response;
    }
```

@Chuhaa Please confirm

**Comment by Chuhaa** [comment]
> **Sample OpenAPI**
> 
> ```yaml
> /pets:
>     post:
>       summary: List all pets
>       description: Show a list of pets in the system
>       operationId: listPets
>       tags:
>         - pets
>         - list
>       parameters:
>         - name: limit
>           in: query
>           description: How many items to return at one time (max 100)
>           required: false
>           schema:
>             type: integer
>             format: int32
>       requestBody:
>         description: Pet
>         content:
>           application/json: {}
>       responses:
>         '200':
>           description: ''
>           content:
>             application/json: {}
> ```
> 
> **Suggested code implementation**
> 
> ```ballerina
> remote isolated function listPets(json payload, int? 'limit = ()) returns json|error {
>         string path = string `/pets`;
>         map<anydata> queryParam = {"limit": 'limit};
>         path = path + check getPathForQueryParam(queryParam);
>         http:Request request = new;
>         request.setPayload(payload, "application/json");
>         json response = check self.clientEp->post(path, request);
>         return response;
>     }
> ```
> 
> @Chuhaa Please confirm

+1
