### ISSUE TITLE
Ballerina CLI tool throws Null pointer exception when generating a Ballerina service/client using an OpenAPI definition

### ISSUE THREAD

**Issue by IsuruMaduranga** [ballerina-platform/openapi-tools#755]
**Description:**

I tried to generate a Ballerina service and a client Stub from an OpenAPI Contract as explained in the [documentation](https://ballerina.io/learn/tooling-guide/cli-tools/openapi/) using OpenAPI definition for JIRA. This gives me the following error stack.

[2021-08-16 23:01:09,287] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at io.ballerina.generators.BallerinaServiceGenerator.createNodeForQueryParam(BallerinaServiceGenerator.java:794)
	at io.ballerina.generators.BallerinaServiceGenerator.getFunctionDefinitionNode(BallerinaServiceGenerator.java:305)
	at io.ballerina.generators.BallerinaServiceGenerator.generateSyntaxTree(BallerinaServiceGenerator.java:245)
	at io.ballerina.openapi.CodeGenerator.generateBallerinaService(CodeGenerator.java:408)
	at io.ballerina.openapi.CodeGenerator.generateBalSource(CodeGenerator.java:218)
	at io.ballerina.openapi.CodeGenerator.generateBothFiles(CodeGenerator.java:113)
	at io.ballerina.openapi.cmd.OpenApiCmd.generateBothFiles(OpenApiCmd.java:298)
	at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:211)
	at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:136)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)

**Steps to reproduce:**
1. Get the OpenAPI definition for JIRA [here](https://github.com/ballerina-platform/ballerinax-openapi-connectors/blob/main/openapi/jira/openapi.json).
2. Run bal openapi -i openapi.json

**Affected Versions:**

Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.5

**OS, DB, other environment details and versions:**
Cent OS 7
OpenJDK 11.0.12 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
This issue cause to query parameter to have an array type without no item type, Those types of query parameters can not be mapped to the ballerina resource query parameter since the ballerina query parameter not support for array with `anydata`. 

In addition to that, I have identified other scenarios we are not supporting from openapi tool , one is we are not supporting the delete method with the request body `required true`. reference  [RFC2616 (HTTP 1.1) ](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.5)

**Comment by lnash94** [comment]
closing the issue since this NPE problem has been fixed in the Ballerina Swanlake beta6 version. Feel free to reopen if you will still face issues after running against the valid openAPI contract. 🙂
