### ISSUE TITLE
Connector generation throws java.lang.NullPointerException for mime type `application/octet-stream`

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#815]
**Description:**

Error log 

```

[2021-12-16 16:16:42,130] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.openapi.generators.client.mime.OctedStreamType.setPayload(OctedStreamType.java:40)
        at io.ballerina.openapi.generators.client.FunctionBodyGenerator.genStatementsForRequestMediaType(FunctionBodyGenerator.java:675)
        at io.ballerina.openapi.generators.client.FunctionBodyGenerator.createRequestBodyStatements(FunctionBodyGenerator.java:629)
        at io.ballerina.openapi.generators.client.FunctionBodyGenerator.handleRequestBodyInOperation(FunctionBodyGenerator.java:480)
        at io.ballerina.openapi.generators.client.FunctionBodyGenerator.getFunctionBodyNode(FunctionBodyGenerator.java:188)
        at io.ballerina.openapi.generators.client.BallerinaClientGenerator.getRemoteFunctionDefinitionNode(BallerinaClientGenerator.java:543)
        at io.ballerina.openapi.generators.client.BallerinaClientGenerator.createRemoteFunctions(BallerinaClientGenerator.java:481)
        at io.ballerina.openapi.generators.client.BallerinaClientGenerator.getClassDefinitionNode(BallerinaClientGenerator.java:240)
        at io.ballerina.openapi.generators.client.BallerinaClientGenerator.generateSyntaxTree(BallerinaClientGenerator.java:199)
        at io.ballerina.openapi.cmd.CodeGenerator.generateClient(CodeGenerator.java:444)
        at io.ballerina.openapi.cmd.CodeGenerator.generateBalSource(CodeGenerator.java:266)
        at io.ballerina.openapi.cmd.CodeGenerator.generate(CodeGenerator.java:150)
        at io.ballerina.openapi.cmd.CodeGenerator.generateClient(CodeGenerator.java:192)
        at io.ballerina.openapi.cmd.OpenApiCmd.generatesClientFile(OpenApiCmd.java:313)
        at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:242)
        at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:151)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

As identified this error is throwing for the request bodies as below
```yaml
requestBody:
        description: Job detail
        content:
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/Job'
```

Please find a sample OpenAPI file [here](https://github.com/ballerina-platform/openapi-connectors/blob/main/openapi/googleapis.bigquery/openapi.yml) 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kasthuriraajan** [comment]
Usually `application/octet-stream` is used to file uploads. As per OpenAPI 3.0 spec (https://swagger.io/specification/), If the property is a `type: string` with `format: binary` or `format: base64` (aka a file object), the default Content-Type is `application/octet-stream`. 
So we can change the `setPayload` method for `OctedStreamType` (https://github.com/ballerina-platform/openapi-tools/blob/f365340e0db9e7b1e96fa6561c2b19abdd73e5a5/openapi-cli/src/main/java/io/ballerina/openapi/generators/client/mime/OctedStreamType.java) in our open API tool as below: 
```
    public void setPayload(List<StatementNode> statementsList, Map.Entry<String, MediaType> mediaTypeEntry) throws Exception {
        if (STRING.equals(mediaTypeEntry.getValue().getSchema().getType()) || mediaTypeEntry.getValue().getSchema().getType() == null) {
            if (BYTE.equals(mediaTypeEntry.getValue().getSchema().getFormat())) {
                payloadName = "encodedRequestBody";
                VariableDeclarationNode encodedVariable = GeneratorUtils.getSimpleStatement("string",
                        payloadName, "payload.toBase64()");
                statementsList.add(encodedVariable);
                setPayload(statementsList, payloadName, javax.ws.rs.core.MediaType.APPLICATION_OCTET_STREAM);
            } else if (BINARY.equals(mediaTypeEntry.getValue().getSchema().getFormat()) || mediaTypeEntry.getValue().getSchema().getFormat() == null) {
                setPayload(statementsList, payloadName, javax.ws.rs.core.MediaType.APPLICATION_OCTET_STREAM);
            } else {
                throw new Exception("The given format is not supported. It should be `binary` or `byte`.");
            }
        } else {
            throw new Exception("The given type is not supported. It should be `string`.");
        }
    }
```

WDYT @aneeshafedo , @indikasampath2000  ?

**Comment by NipunaRanasinghe** [comment]
As per the discussion we had with @shafreenAnfar, @aneeshafedo, @lnash94 and myself, it was decided to use byte arrays (in both client and service generation) to represent the combination of content type `application/octet-stream` with schemas.

However, it would be a nice-to-have feature to improve the client generation logic to deserialise the server response in the client side and, tp retrieve the counterpart Ballerina record as the result.
